/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import z.blog.mapping.tables.ARTICLE;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record16<Integer, String, String, String, Integer, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1453563975;

    /**
     * Setter for <code>t_article.aid</code>.
     */
    public ArticleRecord setAid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_article.aid</code>.
     */
    public Integer getAid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>t_article.title</code>.
     */
    public ArticleRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>t_article.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>t_article.flag</code>.
     */
    public ArticleRecord setFlag(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>t_article.flag</code>.
     */
    public String getFlag() {
        return (String) get(2);
    }

    /**
     * Setter for <code>t_article.content</code>.
     */
    public ArticleRecord setContent(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>t_article.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>t_article.author_id</code>.
     */
    public ArticleRecord setAuthorId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>t_article.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>t_article.type</code>.
     */
    public ArticleRecord setType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>t_article.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>t_article.format</code>.
     */
    public ArticleRecord setFormat(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>t_article.format</code>.
     */
    public String getFormat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>t_article.tag</code>.
     */
    public ArticleRecord setTag(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>t_article.tag</code>.
     */
    public String getTag() {
        return (String) get(7);
    }

    /**
     * Setter for <code>t_article.category</code>.
     */
    public ArticleRecord setCategory(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>t_article.category</code>.
     */
    public String getCategory() {
        return (String) get(8);
    }

    /**
     * Setter for <code>t_article.history</code>.
     */
    public ArticleRecord setHistory(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>t_article.history</code>.
     */
    public Integer getHistory() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>t_article.comment</code>.
     */
    public ArticleRecord setComment(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>t_article.comment</code>.
     */
    public Integer getComment() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>t_article.allow_comment</code>.
     */
    public ArticleRecord setAllowComment(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>t_article.allow_comment</code>.
     */
    public Integer getAllowComment() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>t_article.create_time</code>.
     */
    public ArticleRecord setCreateTime(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>t_article.create_time</code>.
     */
    public Integer getCreateTime() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>t_article.update_time</code>.
     */
    public ArticleRecord setUpdateTime(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>t_article.update_time</code>.
     */
    public Integer getUpdateTime() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>t_article.status</code>.
     */
    public ArticleRecord setStatus(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>t_article.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>t_article.sort</code>.
     */
    public ArticleRecord setSort(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>t_article.sort</code>.
     */
    public Integer getSort() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, String, String, String, Integer, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, String, String, String, Integer, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ARTICLE.T_ARTICLE.AID;
    }

    @Override
    public Field<String> field2() {
        return ARTICLE.T_ARTICLE.TITLE;
    }

    @Override
    public Field<String> field3() {
        return ARTICLE.T_ARTICLE.FLAG;
    }

    @Override
    public Field<String> field4() {
        return ARTICLE.T_ARTICLE.CONTENT;
    }

    @Override
    public Field<Integer> field5() {
        return ARTICLE.T_ARTICLE.AUTHOR_ID;
    }

    @Override
    public Field<String> field6() {
        return ARTICLE.T_ARTICLE.TYPE;
    }

    @Override
    public Field<String> field7() {
        return ARTICLE.T_ARTICLE.FORMAT;
    }

    @Override
    public Field<String> field8() {
        return ARTICLE.T_ARTICLE.TAG;
    }

    @Override
    public Field<String> field9() {
        return ARTICLE.T_ARTICLE.CATEGORY;
    }

    @Override
    public Field<Integer> field10() {
        return ARTICLE.T_ARTICLE.HISTORY;
    }

    @Override
    public Field<Integer> field11() {
        return ARTICLE.T_ARTICLE.COMMENT;
    }

    @Override
    public Field<Integer> field12() {
        return ARTICLE.T_ARTICLE.ALLOW_COMMENT;
    }

    @Override
    public Field<Integer> field13() {
        return ARTICLE.T_ARTICLE.CREATE_TIME;
    }

    @Override
    public Field<Integer> field14() {
        return ARTICLE.T_ARTICLE.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field15() {
        return ARTICLE.T_ARTICLE.STATUS;
    }

    @Override
    public Field<Integer> field16() {
        return ARTICLE.T_ARTICLE.SORT;
    }

    @Override
    public Integer component1() {
        return getAid();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getFlag();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public Integer component5() {
        return getAuthorId();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public String component7() {
        return getFormat();
    }

    @Override
    public String component8() {
        return getTag();
    }

    @Override
    public String component9() {
        return getCategory();
    }

    @Override
    public Integer component10() {
        return getHistory();
    }

    @Override
    public Integer component11() {
        return getComment();
    }

    @Override
    public Integer component12() {
        return getAllowComment();
    }

    @Override
    public Integer component13() {
        return getCreateTime();
    }

    @Override
    public Integer component14() {
        return getUpdateTime();
    }

    @Override
    public Integer component15() {
        return getStatus();
    }

    @Override
    public Integer component16() {
        return getSort();
    }

    @Override
    public Integer value1() {
        return getAid();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getFlag();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public Integer value5() {
        return getAuthorId();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public String value7() {
        return getFormat();
    }

    @Override
    public String value8() {
        return getTag();
    }

    @Override
    public String value9() {
        return getCategory();
    }

    @Override
    public Integer value10() {
        return getHistory();
    }

    @Override
    public Integer value11() {
        return getComment();
    }

    @Override
    public Integer value12() {
        return getAllowComment();
    }

    @Override
    public Integer value13() {
        return getCreateTime();
    }

    @Override
    public Integer value14() {
        return getUpdateTime();
    }

    @Override
    public Integer value15() {
        return getStatus();
    }

    @Override
    public Integer value16() {
        return getSort();
    }

    @Override
    public ArticleRecord value1(Integer value) {
        setAid(value);
        return this;
    }

    @Override
    public ArticleRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ArticleRecord value3(String value) {
        setFlag(value);
        return this;
    }

    @Override
    public ArticleRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ArticleRecord value5(Integer value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public ArticleRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public ArticleRecord value7(String value) {
        setFormat(value);
        return this;
    }

    @Override
    public ArticleRecord value8(String value) {
        setTag(value);
        return this;
    }

    @Override
    public ArticleRecord value9(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ArticleRecord value10(Integer value) {
        setHistory(value);
        return this;
    }

    @Override
    public ArticleRecord value11(Integer value) {
        setComment(value);
        return this;
    }

    @Override
    public ArticleRecord value12(Integer value) {
        setAllowComment(value);
        return this;
    }

    @Override
    public ArticleRecord value13(Integer value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ArticleRecord value14(Integer value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ArticleRecord value15(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public ArticleRecord value16(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public ArticleRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(ARTICLE.T_ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Integer aid, String title, String flag, String content, Integer authorId, String type, String format, String tag, String category, Integer history, Integer comment, Integer allowComment, Integer createTime, Integer updateTime, Integer status, Integer sort) {
        super(ARTICLE.T_ARTICLE);

        set(0, aid);
        set(1, title);
        set(2, flag);
        set(3, content);
        set(4, authorId);
        set(5, type);
        set(6, format);
        set(7, tag);
        set(8, category);
        set(9, history);
        set(10, comment);
        set(11, allowComment);
        set(12, createTime);
        set(13, updateTime);
        set(14, status);
        set(15, sort);
    }
}
