/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import z.blog.mapping.tables.ATTACH;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttachRecord extends UpdatableRecordImpl<AttachRecord> implements Record6<Integer, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1707565682;

    /**
     * Setter for <code>t_attach.aid</code>.
     */
    public AttachRecord setAid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.aid</code>.
     */
    public Integer getAid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>t_attach.name</code>.
     */
    public AttachRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>t_attach.type</code>.
     */
    public AttachRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>t_attach.key</code>.
     */
    public AttachRecord setKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>t_attach.created</code>.
     */
    public AttachRecord setCreated(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.created</code>.
     */
    public Integer getCreated() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>t_attach.url</code>.
     */
    public AttachRecord setUrl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>t_attach.url</code>.
     */
    public String getUrl() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ATTACH.T_ATTACH.AID;
    }

    @Override
    public Field<String> field2() {
        return ATTACH.T_ATTACH.NAME;
    }

    @Override
    public Field<String> field3() {
        return ATTACH.T_ATTACH.TYPE;
    }

    @Override
    public Field<String> field4() {
        return ATTACH.T_ATTACH.KEY;
    }

    @Override
    public Field<Integer> field5() {
        return ATTACH.T_ATTACH.CREATED;
    }

    @Override
    public Field<String> field6() {
        return ATTACH.T_ATTACH.URL;
    }

    @Override
    public Integer component1() {
        return getAid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getKey();
    }

    @Override
    public Integer component5() {
        return getCreated();
    }

    @Override
    public String component6() {
        return getUrl();
    }

    @Override
    public Integer value1() {
        return getAid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getKey();
    }

    @Override
    public Integer value5() {
        return getCreated();
    }

    @Override
    public String value6() {
        return getUrl();
    }

    @Override
    public AttachRecord value1(Integer value) {
        setAid(value);
        return this;
    }

    @Override
    public AttachRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AttachRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public AttachRecord value4(String value) {
        setKey(value);
        return this;
    }

    @Override
    public AttachRecord value5(Integer value) {
        setCreated(value);
        return this;
    }

    @Override
    public AttachRecord value6(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public AttachRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttachRecord
     */
    public AttachRecord() {
        super(ATTACH.T_ATTACH);
    }

    /**
     * Create a detached, initialised AttachRecord
     */
    public AttachRecord(Integer aid, String name, String type, String key, Integer created, String url) {
        super(ATTACH.T_ATTACH);

        set(0, aid);
        set(1, name);
        set(2, type);
        set(3, key);
        set(4, created);
        set(5, url);
    }
}
