/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import z.blog.mapping.tables.META;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaRecord extends UpdatableRecordImpl<MetaRecord> implements Record7<Integer, String, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1712424610;

    /**
     * Setter for <code>t_meta.mid</code>.
     */
    public MetaRecord setMid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.mid</code>.
     */
    public Integer getMid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>t_meta.name</code>.
     */
    public MetaRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>t_meta.slug</code>.
     */
    public MetaRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>t_meta.type</code>.
     */
    public MetaRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>t_meta.description</code>.
     */
    public MetaRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>t_meta.count</code>.
     */
    public MetaRecord setCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>t_meta.sort</code>.
     */
    public MetaRecord setSort(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>t_meta.sort</code>.
     */
    public Integer getSort() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return META.T_META.MID;
    }

    @Override
    public Field<String> field2() {
        return META.T_META.NAME;
    }

    @Override
    public Field<String> field3() {
        return META.T_META.SLUG;
    }

    @Override
    public Field<String> field4() {
        return META.T_META.TYPE;
    }

    @Override
    public Field<String> field5() {
        return META.T_META.DESCRIPTION;
    }

    @Override
    public Field<Integer> field6() {
        return META.T_META.COUNT;
    }

    @Override
    public Field<Integer> field7() {
        return META.T_META.SORT;
    }

    @Override
    public Integer component1() {
        return getMid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSlug();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer component6() {
        return getCount();
    }

    @Override
    public Integer component7() {
        return getSort();
    }

    @Override
    public Integer value1() {
        return getMid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSlug();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Integer value6() {
        return getCount();
    }

    @Override
    public Integer value7() {
        return getSort();
    }

    @Override
    public MetaRecord value1(Integer value) {
        setMid(value);
        return this;
    }

    @Override
    public MetaRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MetaRecord value3(String value) {
        setSlug(value);
        return this;
    }

    @Override
    public MetaRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public MetaRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public MetaRecord value6(Integer value) {
        setCount(value);
        return this;
    }

    @Override
    public MetaRecord value7(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public MetaRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaRecord
     */
    public MetaRecord() {
        super(META.T_META);
    }

    /**
     * Create a detached, initialised MetaRecord
     */
    public MetaRecord(Integer mid, String name, String slug, String type, String description, Integer count, Integer sort) {
        super(META.T_META);

        set(0, mid);
        set(1, name);
        set(2, slug);
        set(3, type);
        set(4, description);
        set(5, count);
        set(6, sort);
    }
}
