/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import z.blog.mapping.tables.OPTION;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionRecord extends UpdatableRecordImpl<OptionRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 843704919;

    /**
     * Setter for <code>t_option.name</code>.
     */
    public OptionRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_option.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>t_option.value</code>.
     */
    public OptionRecord setValue(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>t_option.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OPTION.T_OPTION.NAME;
    }

    @Override
    public Field<String> field2() {
        return OPTION.T_OPTION.VALUE;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public OptionRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public OptionRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public OptionRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OptionRecord
     */
    public OptionRecord() {
        super(OPTION.T_OPTION);
    }

    /**
     * Create a detached, initialised OptionRecord
     */
    public OptionRecord(String name, String value) {
        super(OPTION.T_OPTION);

        set(0, name);
        set(1, value);
    }
}
