/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import z.blog.mapping.DefaultSchema;
import z.blog.mapping.tables.records.CommentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class COMMENT extends TableImpl<CommentRecord> {

    private static final long serialVersionUID = -752321931;

    /**
     * The reference instance of <code>t_comment</code>
     */
    public static final COMMENT T_COMMENT = new COMMENT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommentRecord> getRecordType() {
        return CommentRecord.class;
    }

    /**
     * The column <code>t_comment.cid</code>.
     */
    public final TableField<CommentRecord, Integer> CID = createField(DSL.name("cid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>t_comment.aid</code>.
     */
    public final TableField<CommentRecord, Integer> AID = createField(DSL.name("aid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>t_comment.created</code>.
     */
    public final TableField<CommentRecord, Integer> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>t_comment.author</code>.
     */
    public final TableField<CommentRecord, String> AUTHOR = createField(DSL.name("author"), org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>t_comment.mail</code>.
     */
    public final TableField<CommentRecord, String> MAIL = createField(DSL.name("mail"), org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>t_comment.url</code>.
     */
    public final TableField<CommentRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>t_comment.ip</code>.
     */
    public final TableField<CommentRecord, String> IP = createField(DSL.name("ip"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>t_comment.agent</code>.
     */
    public final TableField<CommentRecord, String> AGENT = createField(DSL.name("agent"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>t_comment.content</code>.
     */
    public final TableField<CommentRecord, String> CONTENT = createField(DSL.name("content"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>t_comment.type</code>.
     */
    public final TableField<CommentRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>t_comment.status</code>.
     */
    public final TableField<CommentRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>t_comment.parent</code>.
     */
    public final TableField<CommentRecord, Integer> PARENT = createField(DSL.name("parent"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>t_comment</code> table reference
     */
    public COMMENT() {
        this(DSL.name("t_comment"), null);
    }

    /**
     * Create an aliased <code>t_comment</code> table reference
     */
    public COMMENT(String alias) {
        this(DSL.name(alias), T_COMMENT);
    }

    /**
     * Create an aliased <code>t_comment</code> table reference
     */
    public COMMENT(Name alias) {
        this(alias, T_COMMENT);
    }

    private COMMENT(Name alias, Table<CommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private COMMENT(Name alias, Table<CommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<CommentRecord, Integer> getIdentity() {
        return Internal.createIdentity(COMMENT.T_COMMENT, COMMENT.T_COMMENT.CID);
    }

    @Override
    public UniqueKey<CommentRecord> getPrimaryKey() {
        return Internal.createUniqueKey(COMMENT.T_COMMENT, "pk_t_comment", new TableField[] { COMMENT.T_COMMENT.CID }, true);
    }

    @Override
    public List<UniqueKey<CommentRecord>> getKeys() {
        return Arrays.<UniqueKey<CommentRecord>>asList(
              Internal.createUniqueKey(COMMENT.T_COMMENT, "pk_t_comment", new TableField[] { COMMENT.T_COMMENT.CID }, true)
        );
    }

    @Override
    public COMMENT as(String alias) {
        return new COMMENT(DSL.name(alias), this);
    }

    @Override
    public COMMENT as(Name alias) {
        return new COMMENT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public COMMENT rename(String name) {
        return new COMMENT(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public COMMENT rename(Name name) {
        return new COMMENT(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, Integer, String, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
