/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import z.blog.mapping.DefaultSchema;
import z.blog.mapping.tables.records.MetaRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class META extends TableImpl<MetaRecord> {

    private static final long serialVersionUID = -473313421;

    /**
     * The reference instance of <code>t_meta</code>
     */
    public static final META T_META = new META();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetaRecord> getRecordType() {
        return MetaRecord.class;
    }

    /**
     * The column <code>t_meta.mid</code>.
     */
    public final TableField<MetaRecord, Integer> MID = createField(DSL.name("mid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>t_meta.name</code>.
     */
    public final TableField<MetaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>t_meta.slug</code>.
     */
    public final TableField<MetaRecord, String> SLUG = createField(DSL.name("slug"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>t_meta.type</code>.
     */
    public final TableField<MetaRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>t_meta.description</code>.
     */
    public final TableField<MetaRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>t_meta.count</code>.
     */
    public final TableField<MetaRecord, Integer> COUNT = createField(DSL.name("count"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>t_meta.sort</code>.
     */
    public final TableField<MetaRecord, Integer> SORT = createField(DSL.name("sort"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>t_meta</code> table reference
     */
    public META() {
        this(DSL.name("t_meta"), null);
    }

    /**
     * Create an aliased <code>t_meta</code> table reference
     */
    public META(String alias) {
        this(DSL.name(alias), T_META);
    }

    /**
     * Create an aliased <code>t_meta</code> table reference
     */
    public META(Name alias) {
        this(alias, T_META);
    }

    private META(Name alias, Table<MetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private META(Name alias, Table<MetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<MetaRecord, Integer> getIdentity() {
        return Internal.createIdentity(META.T_META, META.T_META.MID);
    }

    @Override
    public UniqueKey<MetaRecord> getPrimaryKey() {
        return Internal.createUniqueKey(META.T_META, "pk_t_meta", new TableField[] { META.T_META.MID }, true);
    }

    @Override
    public List<UniqueKey<MetaRecord>> getKeys() {
        return Arrays.<UniqueKey<MetaRecord>>asList(
              Internal.createUniqueKey(META.T_META, "pk_t_meta", new TableField[] { META.T_META.MID }, true)
            , Internal.createUniqueKey(META.T_META, "sqlite_autoindex_t_meta_1", new TableField[] { META.T_META.MID }, true)
        );
    }

    @Override
    public META as(String alias) {
        return new META(DSL.name(alias), this);
    }

    @Override
    public META as(Name alias) {
        return new META(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public META rename(String name) {
        return new META(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public META rename(Name name) {
        return new META(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
