/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping.tables;


import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import z.blog.mapping.DefaultSchema;
import z.blog.mapping.tables.records.RelationshipRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RELATIONSHIP extends TableImpl<RelationshipRecord> {

    private static final long serialVersionUID = -1869870083;

    /**
     * The reference instance of <code>t_relationship</code>
     */
    public static final RELATIONSHIP T_RELATIONSHIP = new RELATIONSHIP();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelationshipRecord> getRecordType() {
        return RelationshipRecord.class;
    }

    /**
     * The column <code>t_relationship.aid</code>.
     */
    public final TableField<RelationshipRecord, Integer> AID = createField(DSL.name("aid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>t_relationship.mid</code>.
     */
    public final TableField<RelationshipRecord, Integer> MID = createField(DSL.name("mid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>t_relationship</code> table reference
     */
    public RELATIONSHIP() {
        this(DSL.name("t_relationship"), null);
    }

    /**
     * Create an aliased <code>t_relationship</code> table reference
     */
    public RELATIONSHIP(String alias) {
        this(DSL.name(alias), T_RELATIONSHIP);
    }

    /**
     * Create an aliased <code>t_relationship</code> table reference
     */
    public RELATIONSHIP(Name alias) {
        this(alias, T_RELATIONSHIP);
    }

    private RELATIONSHIP(Name alias, Table<RelationshipRecord> aliased) {
        this(alias, aliased, null);
    }

    private RELATIONSHIP(Name alias, Table<RelationshipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public RELATIONSHIP as(String alias) {
        return new RELATIONSHIP(DSL.name(alias), this);
    }

    @Override
    public RELATIONSHIP as(Name alias) {
        return new RELATIONSHIP(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RELATIONSHIP rename(String name) {
        return new RELATIONSHIP(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RELATIONSHIP rename(Name name) {
        return new RELATIONSHIP(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
