/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import z.blog.mapping.tables.ARTICLE;
import z.blog.mapping.tables.ATTACH;
import z.blog.mapping.tables.META;
import z.blog.mapping.tables.OPTION;
import z.blog.mapping.tables.RELATIONSHIP;
import z.blog.mapping.tables.USER;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 106429630;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>t_article</code>.
     */
    public final ARTICLE T_ARTICLE = ARTICLE.T_ARTICLE;

    /**
     * The table <code>t_attach</code>.
     */
    public final ATTACH T_ATTACH = ATTACH.T_ATTACH;

    /**
     * The table <code>t_meta</code>.
     */
    public final META T_META = META.T_META;

    /**
     * The table <code>t_option</code>.
     */
    public final OPTION T_OPTION = OPTION.T_OPTION;

    /**
     * The table <code>t_relationship</code>.
     */
    public final RELATIONSHIP T_RELATIONSHIP = RELATIONSHIP.T_RELATIONSHIP;

    /**
     * The table <code>t_user</code>.
     */
    public final USER T_USER = USER.T_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ARTICLE.T_ARTICLE,
            ATTACH.T_ATTACH,
            META.T_META,
            OPTION.T_OPTION,
            RELATIONSHIP.T_RELATIONSHIP,
            USER.T_USER);
    }
}
