/*
 * This file is generated by jOOQ.
 */
package z.blog.mapping;


import z.blog.mapping.tables.ARTICLE;
import z.blog.mapping.tables.ATTACH;
import z.blog.mapping.tables.COMMENT;
import z.blog.mapping.tables.LOG;
import z.blog.mapping.tables.META;
import z.blog.mapping.tables.OPTION;
import z.blog.mapping.tables.RELATIONSHIP;
import z.blog.mapping.tables.USER;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>t_article</code>.
     */
    public static final ARTICLE T_ARTICLE = ARTICLE.T_ARTICLE;

    /**
     * The table <code>t_attach</code>.
     */
    public static final ATTACH T_ATTACH = ATTACH.T_ATTACH;

    /**
     * The table <code>t_comment</code>.
     */
    public static final COMMENT T_COMMENT = COMMENT.T_COMMENT;

    /**
     * The table <code>t_log</code>.
     */
    public static final LOG T_LOG = LOG.T_LOG;

    /**
     * The table <code>t_meta</code>.
     */
    public static final META T_META = META.T_META;

    /**
     * The table <code>t_option</code>.
     */
    public static final OPTION T_OPTION = OPTION.T_OPTION;

    /**
     * The table <code>t_relationship</code>.
     */
    public static final RELATIONSHIP T_RELATIONSHIP = RELATIONSHIP.T_RELATIONSHIP;

    /**
     * The table <code>t_user</code>.
     */
    public static final USER T_USER = USER.T_USER;
}
